// 1指定的当前饰r0t0语法的版本，有23

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: pbfile/call.proto

package pbfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//package service;
//指定等会文件生成出来package
type CallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caller   string `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Callee   string `protobuf:"bytes,2,opt,name=callee,proto3" json:"callee,omitempty"`
	CallLine string `protobuf:"bytes,3,opt,name=call_line,json=callLine,proto3" json:"call_line,omitempty"`
}

func (x *CallReq) Reset() {
	*x = CallReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbfile_call_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallReq) ProtoMessage() {}

func (x *CallReq) ProtoReflect() protoreflect.Message {
	mi := &file_pbfile_call_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallReq.ProtoReflect.Descriptor instead.
func (*CallReq) Descriptor() ([]byte, []int) {
	return file_pbfile_call_proto_rawDescGZIP(), []int{0}
}

func (x *CallReq) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *CallReq) GetCallee() string {
	if x != nil {
		return x.Callee
	}
	return ""
}

func (x *CallReq) GetCallLine() string {
	if x != nil {
		return x.CallLine
	}
	return ""
}

type CallRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xnumber   string `protobuf:"bytes,1,opt,name=xnumber,proto3" json:"xnumber,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *CallRes) Reset() {
	*x = CallRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbfile_call_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRes) ProtoMessage() {}

func (x *CallRes) ProtoReflect() protoreflect.Message {
	mi := &file_pbfile_call_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRes.ProtoReflect.Descriptor instead.
func (*CallRes) Descriptor() ([]byte, []int) {
	return file_pbfile_call_proto_rawDescGZIP(), []int{1}
}

func (x *CallRes) GetXnumber() string {
	if x != nil {
		return x.Xnumber
	}
	return ""
}

func (x *CallRes) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_pbfile_call_proto protoreflect.FileDescriptor

var file_pbfile_call_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x41, 0x0a, 0x07, 0x43,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x78, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x78, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0x29,
	0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a,
	0x04, 0x42, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x08, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2e, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pbfile_call_proto_rawDescOnce sync.Once
	file_pbfile_call_proto_rawDescData = file_pbfile_call_proto_rawDesc
)

func file_pbfile_call_proto_rawDescGZIP() []byte {
	file_pbfile_call_proto_rawDescOnce.Do(func() {
		file_pbfile_call_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbfile_call_proto_rawDescData)
	})
	return file_pbfile_call_proto_rawDescData
}

var file_pbfile_call_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbfile_call_proto_goTypes = []interface{}{
	(*CallReq)(nil), // 0: CallReq
	(*CallRes)(nil), // 1: CallRes
}
var file_pbfile_call_proto_depIdxs = []int32{
	0, // 0: CallService.Bind:input_type -> CallReq
	1, // 1: CallService.Bind:output_type -> CallRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbfile_call_proto_init() }
func file_pbfile_call_proto_init() {
	if File_pbfile_call_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbfile_call_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbfile_call_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbfile_call_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbfile_call_proto_goTypes,
		DependencyIndexes: file_pbfile_call_proto_depIdxs,
		MessageInfos:      file_pbfile_call_proto_msgTypes,
	}.Build()
	File_pbfile_call_proto = out.File
	file_pbfile_call_proto_rawDesc = nil
	file_pbfile_call_proto_goTypes = nil
	file_pbfile_call_proto_depIdxs = nil
}
